apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: usermessages
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: usermessages
              servicePort: 8080